// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEhLY6Ywa9po8dQObcKGz-UKch5WhMSuY',
    appId: '1:900388906458:web:07143c30bec19d7b2b4ce3',
    messagingSenderId: '900388906458',
    projectId: 'jatimtour',
    authDomain: 'jatimtour.firebaseapp.com',
    databaseURL: 'https://jatimtour-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jatimtour.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_WDrdvSXmMUeiM61pSAtixOFqcsHd-H8',
    appId: '1:900388906458:android:a36a4916c036a1982b4ce3',
    messagingSenderId: '900388906458',
    projectId: 'jatimtour',
    databaseURL: 'https://jatimtour-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jatimtour.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtAiUBP5KA6RStKnf7fqLDbgMycLF1fRY',
    appId: '1:900388906458:ios:9b112d051fa5886f2b4ce3',
    messagingSenderId: '900388906458',
    projectId: 'jatimtour',
    databaseURL: 'https://jatimtour-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jatimtour.appspot.com',
    iosClientId: '900388906458-72frdjca2nmep1r9p7gf62evhqsnkboq.apps.googleusercontent.com',
    iosBundleId: 'my.id.jatimtour-team.jatimtour',
  );

}