// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEhLY6Ywa9po8dQObcKGz-UKch5WhMSuY',
    appId: '1:900388906458:web:9de107fe232f69172b4ce3',
    messagingSenderId: '900388906458',
    projectId: 'jatimtour',
    authDomain: 'jatimtour.firebaseapp.com',
    storageBucket: 'jatimtour.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_WDrdvSXmMUeiM61pSAtixOFqcsHd-H8',
    appId: '1:900388906458:android:c5f47b425b6766832b4ce3',
    messagingSenderId: '900388906458',
    projectId: 'jatimtour',
    storageBucket: 'jatimtour.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtAiUBP5KA6RStKnf7fqLDbgMycLF1fRY',
    appId: '1:900388906458:ios:f3269d38576bbc192b4ce3',
    messagingSenderId: '900388906458',
    projectId: 'jatimtour',
    storageBucket: 'jatimtour.appspot.com',
    iosClientId: '900388906458-l6j6d7vtcmudq4fages40uso36pemgc2.apps.googleusercontent.com',
    iosBundleId: 'com.example.jatimtour',
  );
}
